version: '3.8'

services:
  # Infrastructure
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fraud_detection
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: fraud_user
      RABBITMQ_DEFAULT_PASS: fraud_pass
    ports:
      - "5672:5672"
      - "15672:15672"

  # Microservices
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://fraud_user:fraud_pass@postgres:5432/fraud_detection
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fraud_user:fraud_pass@rabbitmq:5672

  web-frontend:
    build: ./services/web-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
      - user-service
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:8000/api
      - REACT_APP_USER_SERVICE_URL=http://0.0.0.0:8004

  fraud-agent:
    build: ./services/fraud-agent
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://fraud_user:fraud_pass@postgres:5432/fraud_detection
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fraud_user:fraud_pass@rabbitmq:5672

  data-collector:
    build: ./services/data-collector
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://fraud_user:fraud_pass@postgres:5432/fraud_detection
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fraud_user:fraud_pass@rabbitmq:5672

  pattern-analyzer:
    build: ./services/pattern-analyzer
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://fraud_user:fraud_pass@postgres:5432/fraud_detection
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fraud_user:fraud_pass@rabbitmq:5672

  user-service:
    build: ./services/user-service
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://fraud_user:fraud_pass@postgres:5432/fraud_detection
      - REDIS_URL=redis://redis:6379

  notification-service:
    build: ./services/notification-service
    ports:
      - "8005:8005"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://fraud_user:fraud_pass@rabbitmq:5672

volumes:
  postgres_data: