apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ACCOUNT.dkr.ecr.REGION.amazonaws.com/fraud-detection-api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fraud-detection-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: fraud-detection-secrets
              key: redis-url
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-fraud-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraud-agent
  template:
    metadata:
      labels:
        app: fraud-agent
    spec:
      containers:
      - name: fraud-agent
        image: ACCOUNT.dkr.ecr.REGION.amazonaws.com/fraud-detection-fraud-agent:latest
        ports:
        - containerPort: 8003
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-agent-service
spec:
  selector:
    app: fraud-agent
  ports:
  - port: 8003
    targetPort: 8003