service: fraud-detection-serverless

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    REDIS_URL: ${env:REDIS_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds:*
        - elasticache:*
      Resource: "*"

functions:
  fraudAgent:
    handler: fraud_agent_lambda.handler
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /decide
          method: post
          cors: true
      - http:
          path: /health
          method: get
          cors: true

  dataCollector:
    handler: data_collector_lambda.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /collect
          method: post
          cors: true

  patternAnalyzer:
    handler: pattern_analyzer_lambda.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /analyze
          method: post
          cors: true

  userService:
    handler: user_service_lambda.handler
    timeout: 15
    memorySize: 256
    events:
      - http:
          path: /login
          method: post
          cors: true
      - http:
          path: /profile
          method: get
          cors: true

resources:
  Resources:
    FraudDetectionBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: fraud-detection-web-${self:provider.stage}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

plugins:
  - serverless-python-requirements